SET C51INC=C:\Keil_v5\C51\Inc;C:\Keil_v5\C51\Inc\Atmel
SET C51LIB=C:\Keil_v5\C51\Lib
SET CPU_TYPE=AT89C51
SET CPU_VENDOR=Microchip
SET UV2_TARGET=Target 1
SET CPU_XTAL=0x016E3600
"C:\Keil_v5\C51\BIN\A51.EXE" @".\Objects\STARTUP._ia"
"C:\Keil_v5\C51\BIN\C51.EXE" @".\Objects\SQUARE~1.__I"
"C:\Keil_v5\C51\BIN\BL51.EXE" @".\Objects\DIGITA~1.LNP"
"C:\Keil_v5\C51\BIN\OH51.EXE" ".\Objects\digital_assignment" 
